var fortune = [
	'Conquer your fears or they will conquer you.',
	'Rivers need springs',
	'Do not feat what you dont know.',
	'You will have pleasent surprise.',
	'Whenever possible keep it simple.',
	'Ignore prevoius furtunes. Lucky number 33, 40, 7, 25, 4, 28',
	'Avoid taking unnecessary gamblrd',
	'Marriag lets you annnoy one special person fir tge rest of your life',
	'Run',
	'Make love, nit bugs',
	'The rubber bands are heading in the right direction',
	'Seek out the significance of your problem at this time. Try to understand.',
	'time heals all wounds. Keep your chin up.',
	'Maybe you can live on the moon in the next century.',
	'You will die alone and poorly dressed.',
	'The end is near and it all your fault.',
	'The road to riches is paved with homeworks.',
	'A man with brown eyes has surprise for you.',
	'An alien of some sort will be appearing to you shortly!'.
	'Your ability to juggle many tasks will take you far.',
	'Maybe you should put some shorts on or something if you want to keep fighting evil today.',
	'Dont lose face! Insist on buying dinner for your tablemates. ',
	'Your future is embarrassing. I cant even talk about it without curling right back up.',
	'Is it love or is it pity? Try not to think about it.',
	'He who laughs last is laughing at you. ',
	'Get away from home awhile to restore your energies.',
	'...And then it hits me. Like, I could totally afford all this cheese!',
	'Behold the power of cheese!',
	'It\'s got to be the cheese.',
	'I got the Motts!',
	'I\'d rather not wake up and discover that one of Ponch\'s creations has self-rotated and left our home space hip-deep in squirrels. It would cause talk.',
	'Flying from ground to LEO tended to make a fear of heights either enough to kill you outright, or completely irrelevant for the rest of your life',
	'Who the hell are you and why are you so obscure?! ',
	'Shorter and funnier!',
	'Vote early, vote often. ',
	'I can feel the magic floating in the air.',
	'No, no, listen, don\'t listen to me, listen.',
	'This is not your room.',
	'Compassion is what you\'re good at. I\'m better at complex searches through organized data structures.',
	'Country music - the music that loves you back.',
	'You may like those pants, but your hips hate them.',
	'It is time for you to appologize for your current hair cut and get a new one',
	'Your ass is neither "unmentionably wide" nor "saggy".',
	'Silflay hraka, u embleer rah!',
	'You think that\'s air you\'re breathing now?',
	'Patience is not my virtue.',
	'Do you usually look this sleepy at 4am?',
	'You are a strange, strange little man.',
	'That\'s the one thing about religion I am absolutely not willing to dispense with--much, much better curse words.', 
	'"Um...is it magic?" "A feather from the wing of an angel made of dust? The fact that it exists is magic."',
	'I found Jesus! He was behind the couch the whole time.',
	'We ain\'t wrong, we ain\'t sorry, and it\'s probably gonna happen again.',
	'It is now safe to take off your pants.',
	'It\'s time for another rousing game of "Pant, Pants, Who\'s Got The Pants?"',
	'Spectacles, testicles, wallet, watch.',
	'I must say I find television very educational. The minute somebody turns it on, I go to the library and read a good book.',
	'These disks tell a story. Story about good, story about bad.',
	'And here we have a lizard that eats people. That\'s always popular.',
	'I used to think I was a child; now I think I am an adult -- not because I no longer do childish things, but because those I call adults are no more mature than I am. ',
	'Someone who listens to the equipment instead of the music.',
	'Pray: To ask that the laws of the universe be annulled in behalf of a single petitioner confessedly unworthy. ',
	'Wasting time is an important part of living.',
	'... A triumph over the forces of suck. ',
	'If God wanted us to vote, He\'d have given us candidates!',
	'Before I read the chapter on ternary search tries, my life was a mess. It was a real rat-infested cesspool! But this book helped to set me straight.',
	'You keep trying to pick a fight, but I\'m still just happy you\'re still alive.',
	'I\'m your wife! I\'m the greatest good you\'re ever gonna get!',
	'...For fame\'s a weed, but repute is a slow-growing oak, and all we can do during our lifetimes is to hop around like squirrels and plant acorns.',
	'She\s making that face again. Must be passing gas!',
	'When you make that face, you\re calculating tip',
	'Bumper sticker: Migratory lifeform with a tropism for bookstores.',
	'Happiness is an inside job.'
];

exports.getFortune = function(){
	var index = Math.floor(Math.random()* fortune.length);
	return fortune[index];
};